#!/usr/bin/env bun
/**
 * Build a standalone single-file executable with Bun.
 *
 * Bun `--compile` currently cannot be combined with `--splitting`, and Bun's
 * bundler output can be fragile on large dependency graphs (Ink/yoga-layout
 * rely on top-level await). To keep a true "one file download" experience, we:
 *   1) build a split ESM bundle with esbuild (works with TLA),
 *   2) pack that bundle + required runtime assets into a zip payload,
 *   3) compile a tiny bootstrap executable that extracts & runs the bundle.
 *
 * The produced executable is still a single file; it just materializes its JS
 * bundle into a cache directory on first run.
 */

import { createHash } from 'node:crypto'
import {
  chmodSync,
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import * as esbuild from 'esbuild'
import { zipSync } from 'fflate'

function platformArchSuffix() {
  const platform = process.platform
  const arch = process.arch
  return `${platform}-${arch}`
}

function outFileForCurrentPlatform() {
  const suffix = platformArchSuffix()
  const ext = process.platform === 'win32' ? '.exe' : ''
  return join('dist', 'bin', suffix, `kode${ext}`)
}

function runOrThrow(cmd) {
  const proc = Bun.spawnSync({
    cmd,
    stdout: 'inherit',
    stderr: 'inherit',
  })

  if (proc.exitCode !== 0) {
    throw new Error(`Command failed (${proc.exitCode}): ${cmd.join(' ')}`)
  }
}

function sha256Hex(bytes) {
  return createHash('sha256').update(bytes).digest('hex')
}

function ensureDir(dirPath) {
  mkdirSync(dirPath, { recursive: true })
}

function copyDirIfExists(srcDir, destDir) {
  if (!existsSync(srcDir)) return false
  ensureDir(dirname(destDir))
  cpSync(srcDir, destDir, { recursive: true })
  return true
}

function listFilesRecursive(rootDir) {
  const out = []
  const stack = [rootDir]

  while (stack.length > 0) {
    const dir = stack.pop()
    if (!dir) continue

    let entries = []
    try {
      entries = readdirSync(dir, { withFileTypes: true })
    } catch {
      continue
    }

    for (const ent of entries) {
      const full = join(dir, ent.name)
      if (ent.isDirectory()) {
        stack.push(full)
      } else if (ent.isFile()) {
        out.push(full)
      }
    }
  }

  return out
}

function toZipPath(relPath) {
  // Zip paths always use "/" separators.
  return relPath.split('\\').join('/')
}

function createZipFromDir(dirPath) {
  const files = listFilesRecursive(dirPath)
  /** @type {Record<string, Uint8Array>} */
  const entries = {}

  for (const abs of files) {
    const rel = relative(dirPath, abs)
    const zipName = toZipPath(rel)
    // Read as Buffer; fflate accepts Uint8Array.
    entries[zipName] = new Uint8Array(readFileSync(abs))
  }

  return zipSync(entries, { level: 9 })
}

function writeBootstrapSource(args) {
  const { outfile, zipBase64, zipSha256, version } = args

  // Keep this bootstrap dependency graph tiny: only Node built-ins + fflate.
  // Avoid top-level await to keep Bun's single-file bundler happy.
  const src = `// Generated by scripts/build-binary.mjs (do not edit by hand)
import { mkdirSync, rmSync, existsSync, writeFileSync, readFileSync, chmodSync } from "node:fs";
import { dirname, join, resolve, sep } from "node:path";
import { homedir, tmpdir } from "node:os";
import { pathToFileURL } from "node:url";
import { unzipSync } from "fflate";

const BUNDLE_VERSION = ${JSON.stringify(version)};
const BUNDLE_SHA256 = ${JSON.stringify(zipSha256)};
const BUNDLE_ZIP_BASE64 = ${JSON.stringify(zipBase64)};

function getKodeRoot() {
  // Mirror packages/config/src/dataRoots.ts for KODE_CONFIG_DIR/ANYKODE_CONFIG_DIR overrides.
  const override = (process.env.KODE_CONFIG_DIR || process.env.ANYKODE_CONFIG_DIR || "").trim();
  if (override) return resolve(override.replace(/^~(?=\\/|$)/, homedir()));
  return join(homedir(), ".kode");
}

function ensureWithinRoot(root, candidate) {
  const absRoot = resolve(root);
  const absCand = resolve(candidate);
  return absCand === absRoot || absCand.startsWith(absRoot + sep);
}

function safeJoin(root, rel) {
  const full = join(root, rel);
  if (!ensureWithinRoot(root, full)) throw new Error("Refusing to write outside bundle root");
  return full;
}

function maybeChmodExecutable(filePath) {
  if (process.platform === "win32") return;
  try { chmodSync(filePath, 0o755); } catch {}
}

function extractIfNeeded(extractRoot) {
  const marker = join(extractRoot, ".kode-bundle-sha256");
  try {
    if (existsSync(marker)) {
      const current = readFileSync(marker, "utf8").trim();
      if (current === BUNDLE_SHA256) return;
    }
  } catch {}

  rmSync(extractRoot, { recursive: true, force: true });
  mkdirSync(extractRoot, { recursive: true });

  const zipBytes = Buffer.from(BUNDLE_ZIP_BASE64, "base64");
  const files = unzipSync(new Uint8Array(zipBytes));

  for (const [name, data] of Object.entries(files)) {
    // Defend against zip-slip, even though the payload is build-generated.
    if (!name || name.startsWith("/") || name.startsWith("\\\\") || name.includes("..")) continue;
    const dest = safeJoin(extractRoot, name);
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, Buffer.from(data));

    // Best-effort: mark known embedded binaries executable.
    if (dest.endsWith("/rg") || dest.endsWith("/rg.exe") || dest.endsWith("\\\\rg.exe")) {
      maybeChmodExecutable(dest);
    }
  }

  writeFileSync(marker, BUNDLE_SHA256);
}

async function main() {
  const suffix = \`\${process.platform}-\${process.arch}\`;
  const baseRoot = getKodeRoot();

  let extractRoot = join(baseRoot, "bundled", "kode", \`\${BUNDLE_VERSION}-\${BUNDLE_SHA256.slice(0, 12)}\`, suffix);
  try {
    extractIfNeeded(extractRoot);
  } catch (err) {
    // Fallback to temp if home/cache dirs are not writable.
    extractRoot = join(tmpdir(), "kode", \`\${BUNDLE_VERSION}-\${BUNDLE_SHA256.slice(0, 12)}\`, suffix);
    extractIfNeeded(extractRoot);
  }

  process.env.KODE_PACKAGED = process.env.KODE_PACKAGED || "1";

  const entry = join(extractRoot, "node_modules", "@shareai-lab", "kode", "dispatch.js");
  await import(pathToFileURL(entry).href);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`

  writeFileSync(outfile, src)
}

async function main() {
  const outFile = outFileForCurrentPlatform()
  const outDir = dirname(outFile)

  rmSync(outDir, { recursive: true, force: true })
  mkdirSync(outDir, { recursive: true })

  const suffix = platformArchSuffix()
  const tmpRoot = join('dist', 'binary', suffix)
  const bundleDir = join(tmpRoot, 'bundle-split')
  const stageDir = join(tmpRoot, 'stage')
  const packageDir = join(stageDir, 'node_modules', '@shareai-lab', 'kode')

  rmSync(tmpRoot, { recursive: true, force: true })
  mkdirSync(bundleDir, { recursive: true })
  mkdirSync(packageDir, { recursive: true })

  console.log('🚀 Building standalone executable (Bun --compile)...')
  console.log(`📦 Target: ${suffix}`)
  console.log(`📍 Output: ${outFile}`)

  console.log('🧩 Step 1/3: Build split JS bundle (esbuild)')
  await esbuild.build({
    entryPoints: { dispatch: 'apps/cli/src/dispatch.ts' },
    outdir: bundleDir,
    bundle: true,
    platform: 'node',
    format: 'esm',
    splitting: true,
    target: ['es2022'],
    tsconfig: 'tsconfig.json',
    packages: 'bundle',
    sourcemap: false,
    minify: false,
    entryNames: '[name]',
    chunkNames: 'chunks/[name]-[hash]',
  })

  console.log('📦 Step 2/3: Stage runtime files')
  // Copy bundled JS output into a pseudo npm layout so existing `require.resolve`
  // code paths (skills discovery, etc.) can locate a package.json on disk.
  cpSync(bundleDir, packageDir, { recursive: true })

  // Provide a real package.json on disk for loaders that use require.resolve(.../package.json).
  cpSync('package.json', join(packageDir, 'package.json'))

  // yoga.wasm is loaded via YOGA_WASM_PATH heuristics; keep it beside entrypoints.
  if (existsSync('yoga.wasm')) {
    cpSync('yoga.wasm', join(packageDir, 'yoga.wasm'))
  }

  // Built-in skills (runtime-discoverable).
  copyDirIfExists(
    join('packages', 'builtin-skills', 'skills'),
    join(packageDir, 'packages', 'builtin-skills', 'skills'),
  )
  copyDirIfExists(
    join('resources', 'skills'),
    join(packageDir, 'resources', 'skills'),
  )

  // WebUI assets (best-effort).
  const webuiDest = join(packageDir, 'webui')
  if (!copyDirIfExists(join('dist', 'webui'), webuiDest)) {
    copyDirIfExists(join('apps', 'server', 'static'), webuiDest)
  }

  // Vendor ripgrep (best-effort). We only stage the current platform's files.
  const rgId = `${process.arch}-${process.platform}`
  const rgSrc = join('vendor', 'ripgrep', rgId)
  if (existsSync(rgSrc)) {
    copyDirIfExists(rgSrc, join(packageDir, 'vendor', 'ripgrep', rgId))
    // Ensure permissions for non-windows runs.
    const rgExe = process.platform === 'win32' ? 'rg.exe' : 'rg'
    const stagedRg = join(packageDir, 'vendor', 'ripgrep', rgId, rgExe)
    if (existsSync(stagedRg) && process.platform !== 'win32') {
      try {
        chmodSync(stagedRg, 0o755)
      } catch {}
    }
  }

  // Linux seccomp assets (best-effort). Stage only the current arch.
  if (process.platform === 'linux') {
    const seccompArch =
      process.arch === 'x64' ? 'x64' : process.arch === 'arm64' ? 'arm64' : null

    if (seccompArch) {
      const seccompSrc = join('vendor', 'seccomp', seccompArch)
      if (existsSync(seccompSrc)) {
        copyDirIfExists(
          seccompSrc,
          join(packageDir, 'vendor', 'seccomp', seccompArch),
        )
        const stagedApply = join(
          packageDir,
          'vendor',
          'seccomp',
          seccompArch,
          'apply-seccomp',
        )
        if (existsSync(stagedApply)) {
          try {
            chmodSync(stagedApply, 0o755)
          } catch {}
        }
      }
    }
  }

  console.log('🧷 Step 3/3: Compile bootstrap executable')
  const zipBytes = createZipFromDir(stageDir)
  const zipSha256 = sha256Hex(zipBytes)
  const zipBase64 = Buffer.from(zipBytes).toString('base64')

  const bootstrapPath = join(tmpRoot, 'bootstrap.mjs')
  const version = JSON.parse(readFileSync('package.json', 'utf8')).version
  writeBootstrapSource({
    outfile: bootstrapPath,
    zipBase64,
    zipSha256,
    version,
  })

  runOrThrow([
    'bun',
    'build',
    '--compile',
    '--target=bun',
    '--format=esm',
    '--outfile',
    outFile,
    bootstrapPath,
  ])

  // Best-effort chmod (non-windows).
  if (process.platform !== 'win32') {
    try {
      chmodSync(outFile, 0o755)
    } catch {}
  }

  console.log('✅ Binary build completed')
}

main().catch(err => {
  console.error('❌ Binary build failed:', err)
  process.exit(1)
})
